find_package(PkgConfig REQUIRED)
pkg_check_modules(GTK4 REQUIRED gtk4)

add_library(gtk INTERFACE IMPORTED)
set_target_properties(gtk PROPERTIES
	INTERFACE_INCLUDE_DIRECTORIES "${GTK4_INCLUDE_DIRS}"
	INTERFACE_LINK_DIRECTORIES "${GTK4_LIBRARY_DIRS}"
	INTERFACE_LINK_LIBRARIES "${GTK4_LIBRARIES}")
